// <auto-generated />
using System;
using FinancNet.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinancNet.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200515031630_create_lancamento")]
    partial class create_lancamento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("FinancNet.Models.Categoria", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao")
                        .IsRequired();

                    b.Property<string>("tipo")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("FinancNet.Models.Conta", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao")
                        .IsRequired();

                    b.Property<string>("numero");

                    b.Property<double>("saldo");

                    b.HasKey("id");

                    b.ToTable("conta");
                });

            modelBuilder.Entity("FinancNet.Models.Lancamento", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("categoriaId");

                    b.Property<long>("contaId");

                    b.Property<DateTime>("data");

                    b.Property<string>("descricao");

                    b.Property<string>("tipo");

                    b.Property<double>("valor");

                    b.HasKey("id");

                    b.HasIndex("categoriaId");

                    b.HasIndex("contaId");

                    b.ToTable("lancamento");
                });

            modelBuilder.Entity("FinancNet.Models.Lancamento", b =>
                {
                    b.HasOne("FinancNet.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinancNet.Models.Conta", "conta")
                        .WithMany()
                        .HasForeignKey("contaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
