// <auto-generated />
using FinancNet.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinancNet.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200410165128_create_conta")]
    partial class create_conta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("FinancNet.Models.Conta", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao");

                    b.Property<string>("numero");

                    b.Property<double>("saldo");

                    b.HasKey("id");

                    b.ToTable("conta");
                });
#pragma warning restore 612, 618
        }
    }
}
